services:
- type: web
  name: cloud-web
  runtime: node
  plan: free
  repo: https://github.com/Omonstr0/tp_blueprint
  branch: master
  buildCommand: npm install
  startCommand: npm run start
  envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: cloud-db
        property: connectionString

databases:
- name: cloud-db
  region: frankfurt
  plan: free


